<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Prognostic Model for Predicting Survival in Non Small Cell Lung Cancer Patients</title>

    <link rel="stylesheet" href="style/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="style/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="style/style.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="style/jquery.dataTables.min.css" type="text/css" media="screen"/>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#info').addClass('active');
        });
    </script>
</head>
<body>
<?php include "header.php"; ?>

<div class="col-xs-12 col-sm-6 col-md-10">
    <h4 class="col-xs-12 col-sm-12 col-md-11">
        Citation: <br/><br/>
        <a href="download/nomogram.Rdata">Download the fitted Coxph model (Wang et al nomogram) in R</a><br/><br/>
        An R object "fit" is contained in the RData file, which is generated by the coxph function.<br/><br/>
        <a href="https://qbrc.swmed.edu/"><img class="qbrcImg" src="img/qbrc.jpg"/></a><br/><br/>
        Citation: <br/><br/>

        1. Hoang, T., Xu, R., Schiller, J.H., Bonomi, P. and Johnson, D.H. (2005) Clinical model to predict survival in chemonaive patients with advanced non-small-cell lung cancer treated with third-generation chemotherapy regimens based on eastern cooperative oncology group data. Journal of clinical oncology : official journal of the American Society of Clinical Oncology, 23, 175-183.<br/><br/>

        2. Paesmans, M., Sculier, J.P., Libert, P., Bureau, G., Dabouis, G., Thiriaux, J., Michel, J., Van Cutsem, O., Sergysels, R., Mommen, P. et al. (1995) Prognostic factors for survival in advanced non-small-cell lung cancer: univariate and multivariate analyses including recursive partitioning and amalgamation algorithms in 1,052 patients. The European Lung Cancer Working Party. Journal of clinical oncology : official journal of the American Society of Clinical Oncology, 13, 1221-1230.<br/><br/>

        3. Albain, K.S., Crowley, J.J., LeBlanc, M. and Livingston, R.B. (1991) Survival determinants in extensive-stage non-small-cell lung cancer: the Southwest Oncology Group experience. Journal of clinical oncology : official journal of the American Society of Clinical Oncology, 9, 1618-1626.<br/><br/>

        4. Finkelstein, D.M., Ettinger, D.S. and Ruckdeschel, J.C. (1986) Long-term survivors in metastatic non-small-cell lung cancer: an Eastern Cooperative Oncology Group Study. Journal of clinical oncology : official journal of the American Society of Clinical Oncology, 4, 702-709.



    </h4>


</div>

<!-- Latest compiled and minified JavaScript -->
<script src="js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>

</body>
</html>